apiVersion: v1
data:
    admin: ENC[AES256_GCM,data:AJgPdl17s24=,iv:BZVUhz55uAxGOs/xv5Y0lN26aFHoSIcwxCuK8iQQog0=,tag:3QEQC79ZcN8yc3hgpv3WFw==,type:str]
    password: ENC[AES256_GCM,data:mrvNnHJQCyQ=,iv:t6cRrIVAWUB5lg0sOVYA00IyzSt0/5HFBu3CIvz9+0k=,tag:dFJFB4ZkjIZP/x0B2PK/Mg==,type:str]
kind: Secret
metadata:
    name: linkding-admin
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUzlLNktnWU5KdEc3bmp2
            eUFLa1JQcTJHaWdpNXRqVzgwTFF6Y3NCQVZZCnV0bVZVVHcyMElSclNzenlleWJL
            N1dvWmFBV2tqZUFUQWJ5QS83RDVwYU0KLS0tIDBYZGRzMWJwbFl6TGhrZXZ5VnBh
            MDM0Q2toVWRpbURwZURlMGxYTVlwQVkK3Lhe1+BN8mEToCDPxzwtf0h9HBCxgwD0
            4MdMwdnWZl0gYQD30wDSXnwoYZ4Fj8uQR/wtSKMIhOzzeWZXcEGW4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dpu9fuvqry7mpze03vwnj7esh9tqslctnax6w6c3upae0vpm2s8qqau89m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-09T17:23:45Z"
    mac: ENC[AES256_GCM,data:UEsvCCUmlYbNWuVH1T+c85BKEp0EowoPvgGn3HKlg9k9vBg7NA1AEX20gOwmXM2U+pr1mR7i9TgMunxRoBF9Y1e5/2UyFqIGLpteeWb68vXCw/QFlRGmFNDi4n0Qynj/+DEpPmhtcya4I9kaX+QdO+wvy3yPiQ5OL7yQMiqzwF0=,iv:h/G5FCRG99g9aAn3ytRO4qtDnUm99n/lwxLeK1bRI3s=,tag:7GCYSXC9Y1cC0IvQzh0aOQ==,type:str]
    version: 3.13.0
