apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:ZvOEvKsuF1tXRatIRAqYXgc0KIlGzjsGtyF4CeHoV3D8NJYDWlhT1eI3tB5Gg1bg/HpQEL/PhFfffOpZ80vrWxdbWMhuDOHodIXw5ARKCbQaNJ1AX5No2GhClvX6MYTI+iYBxCWn+1JFAUY5HwGDWoLfogr5WPz8x517VIi+HwzPQ/kUTwEbo7PJuVxyy+0KjpbuxvVtRGwrgiUggWHUjoAixHIcmHShH7Y7Ac0nRDYMdc863dI3aOUuSL6ERuB8u33UvbYgCVduxCg5ux0eul+Ke+dGqM+xkzI3WtwSHJ2YEqj6Q4Qd0peRhTA=,iv:eF6b8X2oVrRXZBGJlrycC4E+LkBG7wvj9GEpEzbjixc=,tag:h5DLGLJk13XUnfnR1xK4YA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSXVBeDFIKzNEbEdITmZW
            TTVOQUVhZGdoN3hhT3JZb2c2TTZvd0RYaW1NCksyQlFOQnQrZGJCOFRjL0VyQ2U5
            WnVlZ3dNRlVsZ3lqQ3hJL0tUWkljSzQKLS0tIDU4V1hVbGF3a1lWZ05JTkllOGtE
            elJYRHZQR0tiQXhZaFF1SUhCNEV3eWMKGsQaqV2VPHcLU9eMWVhLTL7VKWTuYAwV
            idbNyqdoHSkYAwSSbwG2IHFc0QqX25h5bAwWkBZ9mCYF6CKJchOMuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dpu9fuvqry7mpze03vwnj7esh9tqslctnax6w6c3upae0vpm2s8qqau89m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-09T16:49:26Z"
    mac: ENC[AES256_GCM,data:0vv1GDw2zY4kgscWO42FUgKts8Df1evtqVyHQtA7Xi0iup0MpwOBfvwdwV0pugb96yc/fgtiKv6OALz2OfPtwPxcGmkOMi0pXkaRmsxfXshfyOqKwpG19nPLfbJ/bJ22QO5bKaJya9Uff+DuqmVcnIIBB1D8Iz0HYOhB9YVol8g=,iv:ozTkdbDKd6dNgNJ/FJOwXFL1IkalMys9iAipSRDxdLs=,tag:7/9H54c01w72AkHYpXi0Nw==,type:str]
    version: 3.13.0
